### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by Ascinocco** [MarkusFriesen/OrderMe#2]
Hi Markus,

I'm a friend of your brother Alex.
He showed me your OrderMe app and I think it looks pretty cool.
I'm solid in full stack js. I've primarily used Vue and ng2+ on the client but I'm sure I can pick up
on react quickly. I'd like to contribute to this project and was hoping you would let me join you.
I encourage you to view my Github page and personal website https://www.anthonyscinocco.com/

Thank you for the consideration,
Anthony Scinocco
anthonyscinocco@gmail.com

**Comment by MarkusFriesen** [comment]
check out https://github.com/MarkusFriesen/order/issues/3
